version: "3"
services:
  nest-graphql-heroku:
    container_name: nest-graphql-heroku
    image: node:12
    working_dir: /usr/src/app
    volumes:
      - "//nest-graphql:/usr/src/app"
    command: "bash ./run.sh"
    ports:
      - "7001:4000"
    logging:
      driver: "json-file"
      options:
        max-size: "20k"
        max-file: "10"
    environment:
      NODE_ENV: dev
    networks:
      otus-net:
  otus-postgres-db:
    container_name: otus-postgres-db
    image: postgres:12
    ports:
      - "7002:5432"
    environment:
      POSTGRES_USER: duddits
      POSTGRES_PASSWORD: duddits123
      POSTGRES_DB: nest
    volumes:
      - "database-data:/var/lib/postgresql/data"
    logging:
      driver: "json-file"
      options:
        max-size: "20k"
        max-file: "10"
    networks:
      otus-net:
volumes:
  database-data:
networks:
  otus-net:
